### ISSUE TITLE
Unable to build after fresh clone/yarn.

### ISSUE THREAD

**Issue by bsommardahl** [leohxj/reason-rollup-starter#1]
I just cloned the repo and ran yarn. Yarn installed deps without issue, but when I try to run `yarn build` or any other command, I get the following error:
```
byron@mint-18-dev ~/Projects/reason-rollup-starter $ yarn build
yarn run v1.5.1
$ rimraf dist && cross-env NODE_ENV=production rollup -c rollup.config.prod.js
loaded rollup.config.prod.js with warnings
(!) Unused external imports
default imported from external module 'rollup-plugin-bucklescript' but never used
[!] Error: Cannot find module 'rollup-plugin-bucklescript'
Error: Cannot find module 'rollup-plugin-bucklescript'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/byron/Projects/reason-rollup-starter/rollup.config.prod.js:12:48)
    at Module._compile (module.js:652:30)
    at Object.require.extensions..js (/home/byron/Projects/reason-rollup-starter/node_modules/rollup/bin/rollup:20393:19)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c rimraf dist && cross-env NODE_ENV=production rollup -c rollup.config.prod.js
Directory: /home/byron/Projects/reason-rollup-starter
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/byron/Projects/reason-rollup-starter/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Here are my versions:
```
byron@mint-18-dev ~/Projects/reason-rollup-starter $ node -v
v8.10.0
byron@mint-18-dev ~/Projects/reason-rollup-starter $ yarn -v
1.5.1
```

**Comment by ridhoassuryadi** [comment]
hi @bsommardahl , you can check my fork
 https://github.com/muhammadridho/reason-rollup-starter

**Comment by leohxj** [comment]
@muhammadridho thanks.
